/* ============================================================
   WHO BROKE THE BUSINESS? — game data
   Roles, role perks/blind spots, decision tickets with
   consequences, and Agentforce capability cards.
   ============================================================ */

export const CATS = {
  ops: { emoji: '🔥', label: 'OPS' },
  data: { emoji: '📊', label: 'DATA' },
  people: { emoji: '👥', label: 'PEOPLE' },
};

/* Tetris-style ramp: starts slow and generous, tightens every round.
   quota  = correct calls needed to EARN the round's deployment
   escBud = how many escalations your exec capital covers this round */
export const ROUND_CFG = {
  1: { tickets: 5, spawnMs: 4200, triageSec: 32, escalateMs: 15000, quota: 3, escBud: 2 },
  2: { tickets: 8, spawnMs: 3200, triageSec: 32, escalateMs: 13000, quota: 4, escBud: 3 },
  3: { tickets: 12, spawnMs: 2400, triageSec: 34, escalateMs: 11000, quota: 6, escBud: 5 },
  4: { tickets: 18, spawnMs: 1700, triageSec: 34, escalateMs: 10500, quota: 8, escBud: 7 },
  5: { tickets: 90, spawnMs: 90, triageSec: 0, escalateMs: 2400, quota: 0, escBud: 0 },
};

export const GHOST_DECAY = { 1: 1, 2: 0.7, 3: 0.4, 4: 0.15, 5: 0 };
export const DEGRADED_FACTOR = 0.25;

/* stability costs — the business can actually break */
export const DMG = { wrong: 8, ignored: 2, duplicate: 3, overspend: 3 };
/* a degraded agent can only make so much mess per round */
export const MAX_DUPES_PER_ROUND = 2;
export const DEGRADED_MISFIRE_RATE = 0.1;
/* the weekend: you get some stability back between rounds */
export const RECOVERY = 12;
export const HANDLE_TIME_COST = 3; // seconds off the clock: doing it yourself isn't free

const card = (name, emoji, type, value, cat, cap, effect, msg) => ({
  name, emoji, type, value, cat, cap, effect, msg,
});

export const FIX_DATA = card(
  'Fix the Data', '🗄️', 'data', null, 'all',
  'Data 360 (Data Cloud): dedupe, unify, and ground every agent in one customer record',
  'Removes the dirty-data penalty. Every agent performs as advertised.',
  "AI on top of bad data is a power-up that doesn't power anything."
);

/* Weaker-but-real alternatives — no generic "AI Boost" cards */
export const DECOYS = [
  [
    card('Prompt Templates', '📝', 'additive', 300, 'data',
      'Prompt Builder: reusable prompts that help humans draft faster',
      '+300 capacity. Assists your people; never acts for them.',
      'Assist is a start. Autonomy is the goal.'),
    card('Flow Shortcuts', '⚙️', 'additive', 250, 'ops',
      'Flow: click-path automation for one team\'s process',
      '+250 capacity. Automates one lane, ignores the highway.',
      'Local fixes help one lane. Chaos uses all of them.'),
  ],
  [
    card('Chatbot Classic', '💬', 'trigger', 150, 'people',
      'Legacy scripted chatbot: keyword-matched FAQ replies',
      '+150 capacity. Answers questions; cannot resolve them.',
      'Scripts answer. Agents resolve. Customers can tell.'),
  ],
  [
    card('Dashboard Pack', '📊', 'multiplier', 1.2, 'data',
      'CRM Analytics: more dashboards on the same fragmented data',
      '×1.2 impact. You will see the chaos in higher resolution.',
      "Seeing isn't solving."),
    card('Approval Matrix', '🧾', 'multiplier', 1.3, 'ops',
      'Flow approvals: routed sign-offs with an audit trail',
      '×1.3 impact. The chaos now waits politely in a queue.',
      'Process without intelligence is just slower chaos.'),
  ],
  [
    card('Point Integrations', '🔌', 'orchestrator', 1.6, 'all',
      'Custom one-to-one integrations between every pair of tools',
      '×1.6 impact. N² wires, each with its own failure mode.',
      'Wiring tools together is not agents working together.'),
    card('RPA Scripts', '🤖', 'orchestrator', 1.7, 'all',
      'Screen-scraping macros replaying human clicks',
      '×1.7 impact. Breaks the day anyone moves a button.',
      'Automation that imitates humans inherits their bottlenecks.'),
  ],
];

/* Consolation pick when the deployment is not earned */
export const WITHHELD_CARD = card(
  'Contractor Stopgap', '🧑‍💻', 'additive', 120, 'ops',
  'Two contractors and a shared inbox',
  '+120 capacity. Burns budget, leaves when the contract does.',
  'Headcount is not a system.'
);

/* t(text, cat, right, ctx, out{handle,route,escalate}) */
const t = (text, cat, right, ctx, out) => ({ text, cat, right, ctx, out });

export const ROLES = [
  {
    key: 'ceo', name: 'CEO', emoji: '👩‍💼', tagline: 'Grow the business.', base: 100,
    mission: 'Get one number the whole company believes.',
    metric: 'CROSS-SILO VISIBILITY',
    win: 'Every team reports the same revenue number. On purpose.',
    victory: 'One source of truth. Every team, one number. The board deck finally agrees with itself.',
    perk: { name: 'BOARD INSTINCT', cat: 'data', desc: 'Years in the boardroom: you read reporting conflicts instantly. 📊 DATA items arrive pre-assessed.' },
    blind: { name: 'FRONTLINE BLINDNESS', cat: 'people', desc: "You're four layers from the work. 👥 PEOPLE items reach you with the detail stripped out." },
    actions: {
      handle: { label: 'DECIDE MYSELF', meaning: 'You make the call personally tonight. Costs you 3 seconds of the clock.' },
      route: { label: 'SEND TO DEPT HEAD', meaning: 'A department head owns it. Free, but they only act inside their silo.' },
      escalate: { label: 'TAKE TO BOARD', meaning: 'Board-level attention. Limited capital — spend it on real threats.' },
    },
    waves: [
      ['MONDAY, 8:04 AM', 'Two teams sent you different revenue numbers for the same quarter. Both cc\'d the board.'],
      ['BOARD PREP WEEK', 'The deck contradicts itself on slides 4, 9, and 31. The meeting is Thursday.'],
      ['REORG RUMORS', 'Three departments claim the same project. None are working on it.'],
      ['EARNINGS WEEK', 'Everyone wants a narrative. Nobody has the data.'],
      ['THE PERFECT STORM', 'Activist investor. Leaked memo. And the KPI dashboard just went down.'],
    ],
    tickets: [
      t('Sales reports $4.0M for Q3. Finance reports $2.8M.', 'data', 'escalate',
        'Both numbers are already in the board pre-read. Gap is 30% of the quarter.',
        { handle: 'You pick the middle number. It appears in the 10-Q. Legal is not amused.',
          route: 'Each team "confirms" their own figure. You now have two confident numbers.',
          escalate: 'You flag it before the pre-read locks. Both teams reconcile to one source. Correct.' }),
      t('Ops runs on a spreadsheet only Dave understands. Dave gave notice.', 'people', 'route',
        'Dave leaves in 11 days. Nobody else has opened the file.',
        { handle: 'You spend your evening in someone else\'s macros. Dave still leaves.',
          route: 'The dept head assigns two people to shadow Dave and document it. Correct.',
          escalate: "The board hears you can't operate without one analyst. That's the story now." }),
      t('Board deck v47_FINAL_final2.pptx contradicts v46.', 'data', 'handle',
        'Only slide 12 differs, and you wrote both versions.',
        { handle: 'You reconcile the slide yourself in four minutes. Correct — this one is yours.',
          route: 'A dept head guesses which version you meant. They guess wrong.',
          escalate: 'You escalate your own typo to the board. Capital burned for nothing.' }),
      t('Two departments launched the same product this morning.', 'ops', 'escalate',
        'Both press releases are live. Customers can buy both. Pricing differs by 40%.',
        { handle: 'You pull one page down quietly. The other team escalates you instead.',
          route: 'Each dept insists theirs is the real launch. The market watches.',
          escalate: 'You halt both, unify the offer, and reissue one release. Correct.' }),
      t('All-hands question: "What is our strategy?" — from the strategy team.', 'people', 'handle',
        "It's a question about narrative. You are the narrative.",
        { handle: 'You answer it plainly, on the record, in your own words. Correct.',
          route: 'You forward the question about strategy to the strategy team. It circulates.',
          escalate: 'The board learns your strategy team is asking what the strategy is.' }),
      t('Regional office reports in a different currency. Sometimes.', 'data', 'route',
        'Three of eleven months are unconverted. Finance ops owns the mapping.',
        { handle: 'You rebuild three months of conversions by hand. It happens again next quarter.',
          route: 'Finance ops fixes the mapping at the source. Correct.',
          escalate: 'You bring a currency field to the board. They ask why you are here.' }),
    ],
    cards: [
      card('The Blueprint Builder', '📐', 'additive', 500, 'ops',
        'Agentforce + Flow: automates routine approvals, reporting requests, and status chasing',
        '+500 capacity once integrated. Takes routine 🔥 OPS items end-to-end.',
        'Routine work is the first thing agents should own.'),
      card('The Strategic Ear', '👂', 'trigger', 250, 'people',
        'Agentforce observability across teams: surfaces frontline signal before it becomes a crisis',
        '+250 capacity. Pounces on 👥 PEOPLE items — and clears your blind spot.',
        "Your agents see the context your seat can't."),
      card('Cross-Cloud Orchestrator', '☁️', 'multiplier', 1.5, 'data',
        'Cross-cloud automation: one workflow spanning Sales, Service, and Finance',
        '×1.5 impact. Compounds every agent below it across silos.',
        'Silos are a speed tax. This is the refund.'),
      card('The Company Brain', '🧠', 'orchestrator', 2.0, 'all',
        'Multi-agent orchestration (Atlas Reasoning Engine): agents coordinating on one plan',
        '×2.0 impact. Links every agent you have deployed into one system.',
        'Agents that coordinate beat agents that coexist.'),
    ],
  },

  {
    key: 'cfo', name: 'CFO', emoji: '💰', tagline: 'Protect the bottom line.', base: 100,
    mission: 'Cut cost-per-resolution without cutting corners.',
    metric: '$ PROTECTED',
    win: 'Cost per resolution down 62%. Duplicate tools: zero.',
    victory: 'Every dollar accounted for. The bottom line started protecting itself.',
    perk: { name: 'LEDGER EYE', cat: 'data', desc: 'You read a ledger like a sentence. 📊 DATA items arrive pre-assessed.' },
    blind: { name: 'CUSTOMER BLINDNESS', cat: 'people', desc: 'Nobody sends you sentiment. 👥 PEOPLE items reach you with the detail stripped out.' },
    actions: {
      handle: { label: 'APPROVE MYSELF', meaning: 'You sign it personally. Costs you 3 seconds of the clock.' },
      route: { label: 'SEND TO AUDIT', meaning: 'Audit owns it on a 2-day SLA. Free, but slow and narrow.' },
      escalate: { label: 'FREEZE + ESCALATE', meaning: 'Halts the money and wakes the controller. Limited capital.' },
    },
    waves: [
      ['MONDAY, 8:04 AM', 'Three tools that do the same job all auto-renewed at midnight.'],
      ['REFUND MELTDOWN', 'Your chatbot has been issuing refunds. Enthusiastically.'],
      ['AUDIT SEASON', 'The auditors have questions. The spreadsheet has circular references.'],
      ['BUDGET LOCKDOWN', 'Every department wants more. The numbers want less.'],
      ['THE PERFECT STORM', 'Quarter close, a rogue chatbot, and the cloud bill just doubled itself.'],
    ],
    tickets: [
      t('Refund issued: $40,000. And $0.00. Twice.', 'data', 'escalate',
        'Nine times the largest refund ever approved. No approver logged. Funds not yet settled.',
        { handle: 'You reverse it quietly. Auditors find the gap in Q4 and ask who hid it.',
          route: 'Audit opens a 2-day ticket. The payment settles on day one.',
          escalate: 'You freeze the payment and claw it back before settlement. Correct.' }),
      t('Three tools doing the same job. All auto-renewed last night.', 'data', 'route',
        '$180K/yr combined. Contracts have a 30-day cancellation window that is still open.',
        { handle: 'You cancel two yourself and break a workflow nobody told you about.',
          route: 'Audit maps usage and cancels the redundant two inside the window. Correct.',
          escalate: 'The controller confirms that yes, you bought three of the same thing.' }),
      t('Expense report: "team morale" — $18,500.', 'ops', 'handle',
        'One line item, one submitter, policy cap is $2,000. Straightforward call.',
        { handle: 'You reject it and cite the policy in one line. Correct.',
          route: 'Audit spends two days confirming $18,500 is more than $2,000.',
          escalate: 'You take a rejected expense report to the controller. Capital burned.' }),
      t('Chatbot promised a customer "unlimited refunds, forever."', 'people', 'escalate',
        'In writing, to a $2M account, and screenshotted on social. Legal exposure is live.',
        { handle: 'You email the customer a correction. The screenshot keeps traveling.',
          route: 'Audit reviews the transcript next week. The thread is trending today.',
          escalate: 'Legal and comms get it inside the hour and contain it. Correct.' }),
      t('Invoice #4471 is 90 days late. Customer: "what invoice?"', 'ops', 'route',
        '$46K, and the customer portal shows no record of it being sent.',
        { handle: 'You chase it personally. It gets paid. The next twelve do not.',
          route: 'Collections re-issues and fixes the send process. Correct.',
          escalate: 'The controller learns you escalate individual invoices.' }),
      t('Cloud bill doubled. Nobody deployed anything.', 'data', 'escalate',
        '+$310K this month, still climbing hourly. Spend curve is vertical.',
        { handle: 'You cap one account. The spend moves to a different account.',
          route: 'Audit investigates on a 2-day SLA. That is $20K of runtime.',
          escalate: 'You freeze provisioning and find the runaway job. Correct.' }),
    ],
    cards: [
      card('Invoice Chaser', '🧾', 'additive', 400, 'ops',
        'Agentforce for Finance: autonomous invoice follow-up and dunning via Flow',
        '+400 capacity once integrated. Owns routine 🔥 OPS collections end-to-end.',
        'Collections should not need a human until a human is needed.'),
      card('Anomaly Watcher', '🚨', 'trigger', 250, 'people',
        'Agentforce observability: flags customer-facing commitments and sentiment risk in real time',
        '+250 capacity. Pounces on 👥 PEOPLE items — and clears your blind spot.',
        "Your agents see the context your seat can't."),
      card('Vendor Auto-Negotiator', '🤝', 'multiplier', 1.5, 'data',
        'Agentforce on contract data: renewal analysis and duplicate-tool detection',
        '×1.5 impact. Compounds savings across every contract.',
        'Three tools, one job, zero surprise renewals.'),
      card('The Ledger Mind', '🧮', 'orchestrator', 2.0, 'all',
        'Multi-agent orchestration: finance agents reconciling against one ledger',
        '×2.0 impact. Links every agent into one auditable system.',
        'Agents that coordinate beat agents that coexist.'),
    ],
  },

  {
    key: 'cto', name: 'CTO', emoji: '💻', tagline: 'Keep the stack from collapsing.', base: 100,
    mission: 'Keep engineers building, not firefighting.',
    metric: 'UPTIME SHIPPED',
    win: 'Tier-1 deflection 78%. Engineering interrupts down 71%.',
    victory: 'The stack held. Engineering is building again — not firefighting.',
    perk: { name: 'ROOT CAUSE', cat: 'ops', desc: 'You can smell a real outage. 🔥 OPS items arrive pre-assessed.' },
    blind: { name: 'REVENUE BLINDNESS', cat: 'data', desc: 'Nobody tells you what a ticket is worth. 📊 DATA items reach you with the detail stripped out.' },
    actions: {
      handle: { label: 'FIX IT MYSELF', meaning: 'You open the terminal personally. Costs you 3 seconds of the clock.' },
      route: { label: 'SEND TO PLATFORM', meaning: 'Platform team owns it in the next sprint. Free, but not today.' },
      escalate: { label: 'PAGE ON-CALL', meaning: 'Wakes the on-call rotation. Limited capital — false pages burn trust.' },
    },
    waves: [
      ['MONDAY, 8:04 AM', 'A support ticket was escalated straight to engineering. Then four more.'],
      ['DEBT COLLECTION', 'The technical debt now has its own technical debt.'],
      ['LEGACY AWAKENS', 'The DOS terminal in the corner is beeping. Nobody will touch it.'],
      ['DEPLOY FREEZE', 'Prod is degraded. Staging is fine. Nobody knows why.'],
      ['THE PERFECT STORM', 'Prod is down, the on-call quit, and the DOS terminal is beeping in Morse code.'],
    ],
    tickets: [
      t('Checkout API returning 500s for 8% of requests.', 'ops', 'escalate',
        'Error rate climbing every minute. Started 6 minutes ago. Payments affected.',
        { handle: 'You debug it alone while the error rate triples behind you.',
          route: 'Platform picks it up next sprint. Checkout is broken now.',
          escalate: 'On-call rolls back the bad deploy in four minutes. Correct.' }),
      t('CI red for 6 days, labeled "known issue".', 'ops', 'route',
        'One flaky integration test. Nothing is actually broken in prod.',
        { handle: 'You fix the flake yourself at 11pm. It comes back Thursday.',
          route: 'Platform owns the flake and quarantines it properly. Correct.',
          escalate: 'You page on-call for a flaky test. Nobody answers next time.' }),
      t('New hire asked what the legacy system does. Silence.', 'people', 'route',
        'Nobody has documented it. Three people know parts of it. All three are busy.',
        { handle: 'You explain it verbally once. The knowledge dies again.',
          route: 'Platform assigns documentation with an owner and a date. Correct.',
          escalate: 'You page on-call to explain the legacy system. At 2am.' }),
      t('Support ticket escalated straight to engineering. Again.', 'people', 'handle',
        'It is a password reset. Fifth one this week routed to a senior engineer.',
        { handle: 'You resolve it in seconds and fix the routing rule. Correct.',
          route: 'Platform queues a password reset for next sprint.',
          escalate: 'You page on-call about a password reset. Trust spent.' }),
      t('Mainframe password was on a sticky note. Sticky note is gone.', 'data', 'escalate',
        'Sole access to payroll and billing. No recovery path documented. Payroll runs Friday.',
        { handle: 'You try eleven guesses and lock the account entirely.',
          route: 'Platform files a ticket. Payroll is Friday.',
          escalate: 'Security opens a recovery path before payroll. Correct.' }),
      t('17 microservices. 1 works.', 'data', 'route',
        'Nothing is on fire. It is architecture debt with no incident attached.',
        { handle: 'You rewrite one service yourself. Sixteen to go.',
          route: 'Platform builds a consolidation plan with owners. Correct.',
          escalate: 'You page on-call about architecture philosophy.' }),
    ],
    cards: [
      card('Bug Triage Protocol', '🐛', 'additive', 500, 'ops',
        'Agentforce Service Agent: Tier-1 ticket classification and deflection',
        '+500 capacity once integrated. Deflects routine 🔥 OPS items before engineering sees them.',
        'Deflection keeps engineers building.'),
      card('SLA Enforcer', '⏱️', 'trigger', 250, 'data',
        'Agentforce observability: ties every incident to the revenue and SLA at risk',
        '+250 capacity. Pounces on 📊 DATA items — and clears your blind spot.',
        "Your agents see the context your seat can't."),
      card('Knowledge Architect', '📚', 'multiplier', 1.5, 'people',
        'Knowledge unification: agents grounded in one current source of truth',
        '×1.5 impact. Every answer compounds instead of contradicting.',
        "Answers from the wiki that's actually current."),
      card('The Systems Conductor', '🎛️', 'orchestrator', 2.0, 'all',
        'Multi-agent orchestration (Atlas Reasoning Engine) across the incident lifecycle',
        '×2.0 impact. Links every agent into one incident-response system.',
        'Agents that coordinate beat agents that coexist.'),
    ],
  },

  {
    key: 'cmo', name: 'CMO', emoji: '📈', tagline: 'Generate leads Sales actually wants.', base: 100,
    mission: 'Fill the pipeline with leads Sales actually wants.',
    metric: 'QUALIFIED PIPELINE',
    win: 'Lead quality up 3.4×. Steves in the CRM: 1 (verified human).',
    victory: 'Sales just asked for MORE leads. Every one is a real person. None of them are named Steve.',
    perk: { name: 'SIGNAL READ', cat: 'data', desc: 'You know a real buying signal from noise. 📊 DATA items arrive pre-assessed.' },
    blind: { name: 'OPS BLINDNESS', cat: 'ops', desc: 'Delivery cost is somebody else\'s dashboard. 🔥 OPS items reach you with the detail stripped out.' },
    actions: {
      handle: { label: 'FIX THE CAMPAIGN', meaning: 'You get into the tool yourself. Costs you 3 seconds of the clock.' },
      route: { label: 'SEND TO SALES OPS', meaning: 'Sales ops owns it this week. Free, but it waits its turn.' },
      escalate: { label: 'KILL + ESCALATE', meaning: 'Stops the send and pulls in leadership. Limited capital.' },
    },
    waves: [
      ['MONDAY, 8:04 AM', 'The funnel chart looks fantastic. The funnel is empty.'],
      ['WRONG LIST', 'The campaign just emailed the churn list a "welcome back!"'],
      ['THE STEVE PROBLEM', 'Every customer in the CRM is named Steve. Every single one.'],
      ['LAUNCH WEEK', 'Five channels, one intern, zero attribution.'],
      ['THE PERFECT STORM', 'Product launch, wrong list, and 40,000 people just got "Hi {FirstName}".'],
    ],
    tickets: [
      t('Campaign is sending to the churn list. 40,000 recipients.', 'data', 'escalate',
        'Send is in progress: 6,000 delivered, 34,000 queued. Subject line: "Welcome back!"',
        { handle: 'You edit the template while the queue keeps draining.',
          route: 'Sales ops reviews it this week. The send finishes in 20 minutes.',
          escalate: 'You kill the send at 6,000 and save the other 34,000. Correct.' }),
      t('Lead name: Steve. Company: Steve. Email: steve.', 'data', 'route',
        '11,400 records with the same pattern. Form validation is the root cause.',
        { handle: 'You clean records by hand. The form keeps making more.',
          route: 'Sales ops fixes validation and dedupes the batch. Correct.',
          escalate: 'You escalate data hygiene to leadership without a plan.' }),
      t('Webinar has 3 registrants. Two are your interns.', 'people', 'handle',
        'It runs Thursday. Promotion never went out — that was your task.',
        { handle: 'You send the promo yourself today. Correct — you own this one.',
          route: 'Sales ops schedules promotion for after the webinar.',
          escalate: 'You bring three registrants to leadership. Capital burned.' }),
      t('Paid ads targeting: "everyone, everywhere". $80K/day.', 'ops', 'escalate',
        'Spend live since midnight, CPL 14× target. Nobody set a cap.',
        { handle: 'You narrow one ad set. The other nine keep spending.',
          route: 'Sales ops reviews budget pacing this week. That is $400K.',
          escalate: 'You pause the account and reset targeting. Correct.' }),
      t('Attribution model says the fax machine drove Q2.', 'data', 'handle',
        'One mis-mapped channel ID in a model you built. Ten-minute fix.',
        { handle: 'You remap the channel yourself. Correct.',
          route: 'Sales ops inherits a model only you understand.',
          escalate: 'You escalate a fax machine to leadership.' }),
      t('Influencer posted the wrong product. It sold out.', 'ops', 'route',
        'Wrong SKU, real demand, and fulfillment cannot cover the orders taken.',
        { handle: 'You post a correction. The orders are already in the system.',
          route: 'Ops and fulfillment reconcile the orders and comms together. Correct.',
          escalate: 'Leadership hears "sold out" and asks why that is a problem.' }),
    ],
    cards: [
      card('Intent Scorer', '🎯', 'additive', 400, 'data',
        'Agentforce + Data 360 segments: intent scoring on unified customer profiles',
        '+400 capacity once integrated. Qualifies routine 📊 DATA items automatically.',
        'Leads Sales wants start with data Sales trusts.'),
      card('Audience Orchestrator', '📣', 'trigger', 250, 'ops',
        'Agentforce campaign guardrails: watches spend, delivery, and send health in real time',
        '+250 capacity. Pounces on 🔥 OPS items — and clears your blind spot.',
        "Your agents see the context your seat can't."),
      card('Micro-Personalization Engine', '🔬', 'multiplier', 1.5, 'people',
        '1:1 personalization on unified profiles — the right message, not the loudest',
        '×1.5 impact. Every touch compounds instead of annoying.',
        'Personal beats loud.'),
      card('Autonomous Campaign Manager', '🚀', 'orchestrator', 2.0, 'all',
        'Multi-agent orchestration: campaign agents planning, testing, and reallocating together',
        '×2.0 impact. Links every agent into one revenue engine.',
        'Agents that coordinate beat agents that coexist.'),
    ],
  },

  {
    key: 'cro', name: 'CRO', emoji: '🤝', tagline: 'Hit your number.', base: 100,
    mission: 'Make the forecast math, not vibes.',
    metric: 'FORECAST ACCURACY',
    win: 'Forecast accuracy 94%. Rep admin time down 80%.',
    victory: 'Number: hit. Forecast: math, not vibes. Reps: actually selling.',
    perk: { name: 'DEAL SENSE', cat: 'people', desc: 'You know which deals are real. 👥 PEOPLE items arrive pre-assessed.' },
    blind: { name: 'PROCESS BLINDNESS', cat: 'ops', desc: 'Compliance detail never reaches the number. 🔥 OPS items reach you with the detail stripped out.' },
    actions: {
      handle: { label: 'WORK IT MYSELF', meaning: 'You get on the phone personally. Costs you 3 seconds of the clock.' },
      route: { label: 'SEND TO DEAL DESK', meaning: 'Deal desk owns it on a 2-day SLA. Free, but not instant.' },
      escalate: { label: 'PULL IN LEADERSHIP', meaning: 'Exec sponsor gets involved. Limited capital — do not cry wolf.' },
    },
    waves: [
      ['MONDAY, 8:04 AM', 'Your reps spent six hours updating CRM fields. They sold nothing.'],
      ['EMPTY FIELDS', 'The CRM is a beautiful, expensive void.'],
      ['FORECAST: VIBES', 'The pipeline review is tomorrow. The methodology is a shrug.'],
      ['QUARTER CRUNCH', 'Every deal is "closing this week." Every week.'],
      ['THE PERFECT STORM', 'Last day of the quarter. The forecast is vibes and the CRM logged everyone out.'],
    ],
    tickets: [
      t('$1.2M renewal date passed. Nobody noticed. The customer did.', 'people', 'escalate',
        'Largest account in the region, now out of contract and taking competitor calls.',
        { handle: 'You call the champion yourself. Procurement has already moved on.',
          route: 'Deal desk works it on a 2-day SLA. The competitor demo is tomorrow.',
          escalate: 'Exec sponsor calls their CFO today and holds the renewal. Correct.' }),
      t('Rep spent 6 hours updating CRM fields. Sold nothing.', 'people', 'route',
        'Pattern across the team, not one rep. Field requirements doubled last quarter.',
        { handle: 'You update this rep\'s records yourself. Thirty other reps are still stuck.',
          route: 'Deal desk trims required fields and automates the rest. Correct.',
          escalate: 'Leadership hears your reps do data entry. They ask what you have been doing.' }),
      t('Discount approved: 90%. Approver: unclear.', 'ops', 'escalate',
        'Below cost, contract unsigned, and it sets precedent for the whole segment.',
        { handle: 'You quietly re-price it. The rep sends the old quote anyway.',
          route: 'Deal desk reviews in 2 days. The customer countersigns tomorrow.',
          escalate: 'You halt the quote before signature and reset the floor. Correct.' }),
      t('Top rep\'s pipeline: 40 deals named "Follow up".', 'people', 'handle',
        'Your best rep, your forecast call tomorrow. One conversation fixes it.',
        { handle: 'You walk the pipeline with them for ten minutes. Correct.',
          route: 'Deal desk emails them a naming convention doc.',
          escalate: 'You escalate deal names to leadership.' }),
      t('Forecast methodology: vibes.', 'ops', 'route',
        'Review is tomorrow. Deal desk owns the scoring model and can rebuild it.',
        { handle: 'You rebuild the forecast in a spreadsheet at midnight. Again next month.',
          route: 'Deal desk implements stage-weighted scoring off real data. Correct.',
          escalate: 'You tell leadership the forecast is vibes with no fix attached.' }),
      t('CRM says the deal closed in 1970.', 'data', 'handle',
        'One record, obvious date-parse error, no revenue impact.',
        { handle: 'You correct the date in fifteen seconds. Correct.',
          route: 'Deal desk opens a 2-day ticket for a typo.',
          escalate: 'You escalate 1970 to leadership.' }),
    ],
    cards: [
      card('Pipeline Hygienist', '🧹', 'additive', 500, 'data',
        'Agentforce SDR: logs every touch, updates every field, chases every follow-up',
        '+500 capacity once integrated. Owns routine 📊 DATA admin end-to-end.',
        'Reps sell. Agents do the admin.'),
      card('Synthetic Coach', '🎓', 'trigger', 250, 'ops',
        'Agentforce deal guardrails: watches pricing, approvals, and contract compliance live',
        '+250 capacity. Pounces on 🔥 OPS items — and clears your blind spot.',
        "Your agents see the context your seat can't."),
      card('Dynamic Margin Pricing', '💹', 'multiplier', 1.5, 'people',
        'Agentforce pricing guidance: guardrailed discounting tied to margin',
        '×1.5 impact. Every deal compounds instead of leaking.',
        'Discounts by math, not panic.'),
      card('The Revenue Engine', '⚙️', 'orchestrator', 2.0, 'all',
        'Multi-agent orchestration: SDR, coach, and pricing agents on one pipeline',
        '×2.0 impact. Links every agent into one number-hitting system.',
        'Agents that coordinate beat agents that coexist.'),
    ],
  },

  {
    key: 'cs', name: 'Head of Customer Service', emoji: '🎧', tagline: 'Keep customers happy.', base: 100,
    mission: 'Resolve honestly — deflect the routine, escalate the real.',
    metric: 'HONEST RESOLUTIONS',
    win: 'Deflection 64% — with zero confidently-wrong answers.',
    victory: 'Queue: empty. CSAT: up. The AI made the right call — 4,000 times in a row.',
    perk: { name: 'CUSTOMER EAR', cat: 'people', desc: 'You hear a customer about to churn. 👥 PEOPLE items arrive pre-assessed.' },
    blind: { name: 'INFRA BLINDNESS', cat: 'ops', desc: 'You get symptoms, never systems. 🔥 OPS items reach you with the detail stripped out.' },
    actions: {
      handle: { label: 'TAKE IT MYSELF', meaning: 'You answer the customer personally. Costs you 3 seconds of the clock.' },
      route: { label: 'SEND TO TIER 2', meaning: 'Tier 2 owns it in queue order. Free, but it waits.' },
      escalate: { label: 'DECLARE INCIDENT', meaning: 'Spins up incident response. Limited capital — false alarms cost credibility.' },
    },
    waves: [
      ['MONDAY, 8:04 AM', 'Wait time is 40 minutes and the hold music has one song.'],
      ['CONFIDENTLY WRONG', 'Your AI just made the wrong call. With total confidence. To a VIP.'],
      ['REGIONAL OUTAGE', 'Everything is down. The status page is all green.'],
      ['CSAT FREEFALL', 'The survey went out mid-outage. The results rhyme with "disaster."'],
      ['THE PERFECT STORM', 'Regional outage, 4-hour queue, and the AI is apologizing to the wrong customers.'],
    ],
    tickets: [
      t('AI told 300 customers the product is discontinued. It is not.', 'people', 'escalate',
        'Confident, wrong, and already quoted in two public reviews. Still replying now.',
        { handle: 'You personally correct three of the three hundred.',
          route: 'Tier 2 works the queue in order. The bot keeps answering.',
          escalate: 'You pull the response, notify all 300, and correct the record. Correct.' }),
      t('Wait time 40 minutes. Queue depth 1,200.', 'ops', 'route',
        'Volume spike, no outage. Staffing and routing are the lever here.',
        { handle: 'You take calls yourself. You clear four of twelve hundred.',
          route: 'Tier 2 re-routes with surge staffing and macros. Correct.',
          escalate: 'You declare an incident for a busy Monday. Credibility spent.' }),
      t('Customer replied "ok" — case auto-closed as resolved.', 'people', 'handle',
        'One case, one bad automation rule, and a customer who is not resolved.',
        { handle: 'You reopen it and answer them yourself. Correct.',
          route: 'Tier 2 gets it back in queue behind 1,200 cases.',
          escalate: 'You declare an incident over the word "ok".' }),
      t('Status page all green. 4,000 customers report the app is down.', 'ops', 'escalate',
        'Regional failure with no alerting. Reports climbing 200/minute.',
        { handle: 'You reply to complaints individually while the region stays down.',
          route: 'Tier 2 triages tickets one by one. The outage continues.',
          escalate: 'You declare the incident, engineering engages, status page corrected. Correct.' }),
      t('VIP stuck in a tier-1 loop for 3 days.', 'people', 'escalate',
        'Top-20 account, renewal in two weeks, three failed handoffs already logged.',
        { handle: 'You answer them yourself. The loop catches the next VIP too.',
          route: 'Tier 2 receives the fourth handoff of the same case.',
          escalate: 'Named owner assigned end-to-end and the loop is fixed. Correct.' }),
      t('"Urgent" tag applied to every ticket, so none are.', 'data', 'route',
        'Tagging rule, not a customer issue. Nothing is burning right now.',
        { handle: 'You retag a hundred tickets by hand overnight.',
          route: 'Tier 2 rewrites the tagging rules at the source. Correct.',
          escalate: 'You declare an incident about tag hygiene.' }),
    ],
    cards: [
      card('Inbox Triage', '📥', 'additive', 400, 'people',
        'Agentforce Service Agent: case classification and routine-case deflection',
        '+400 capacity once integrated. Resolves routine 👥 PEOPLE cases end-to-end.',
        'Deflect the routine. Dignify the complex.'),
      card('Escalation Assistant', '🆘', 'trigger', 250, 'ops',
        'Agentforce observability: correlates ticket spikes with system health in real time',
        '+250 capacity. Pounces on 🔥 OPS items — and clears your blind spot.',
        "Your agents see the context your seat can't."),
      card('Tier-1 Auto-Resolve', '✅', 'multiplier', 1.5, 'data',
        "Service Agent full resolution — with honest handoffs when it isn't sure",
        '×1.5 impact. Deflection that compounds trust instead of spending it.',
        "Deflection that admits what it can't do."),
      card('The Service Mesh', '🕸️', 'orchestrator', 2.0, 'all',
        'Multi-agent orchestration across triage, resolution, and follow-up',
        '×2.0 impact. Links every agent into one service system.',
        'Agents that coordinate beat agents that coexist.'),
    ],
  },
];

export const AMBIENT_NOISE = [
  'URGENT', 'RE: RE: RE:', 'FYI', 'per my last email', 'quick sync?',
  'EOD??', 'circling back', 'as discussed', '@here', 'ping',
];
